import 'jsr:@supabase/functions-js/edge-runtime.d.ts';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const split=name=>(Deno.env.get(name)||'').split(',').map(x=>x.trim()).filter(Boolean);
const pools={groq:split('GROQ_API_KEYS'),openrouter:split('OPENROUTER_API_KEYS'),openai:split('OPENAI_API_KEYS'),gemini:split('GEMINI_API_KEYS'),notion:[1,2,3,4,5].map(i=>(Deno.env.get(`NOTION_API_KEY_${i}`)||'').trim()).filter(Boolean)};
const limits=new Map();
function takeQuota(req){const ip=(req.headers.get('x-forwarded-for')||req.headers.get('cf-connecting-ip')||'public').split(',')[0].trim();const hour=Math.floor(Date.now()/3600000),key=ip+'|'+hour,count=limits.get(key)||0;if(count>=60)return false;limits.set(key,count+1);return true;}
const endpoints={groq:['https:'+'//api.groq.com/openai/v1/chat/completions','llama-3.1-8b-instant'],openrouter:['https:'+'//openrouter.ai/api/v1/chat/completions','openai/gpt-4.1-mini'],openai:['https:'+'//api.openai.com/v1/chat/completions','gpt-4.1-mini']};
const modelCache=new Map();
async function resolveModel(provider,key){if(provider!=='groq')return endpoints[provider][1];const cacheKey='groq:'+key.slice(-8),cached=modelCache.get(cacheKey);if(cached)return cached;try{const r=await fetch('https:'+'//api.groq.com/openai/v1/models',{signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+key}});if(r.ok){const body=await r.json(),ids=(body.data||[]).filter(x=>x.active!==false).map(x=>x.id).filter(Boolean),preferred=['llama-3.3-70b-versatile','openai/gpt-oss-120b','meta-llama/llama-4-scout-17b-16e-instruct','qwen/qwen3-32b','llama-3.1-8b-instant'];const model=preferred.find(x=>ids.includes(x))||ids.find(x=>!/whisper|tts|speech|guard|safeguard|prompt-guard/i.test(x));if(model){modelCache.set(cacheKey,model);return model;}}}catch{}return endpoints.groq[1];}
async function compatible(provider,key,messages,maxTokens){const [url]=endpoints[provider],model=await resolveModel(provider,key),r=await fetch(url,{method:'POST',signal:AbortSignal.timeout(30000),headers:{'Content-Type':'application/json',Authorization:'Bearer '+key,'HTTP-Referer':'https:'+'//asravsitesi.github.io/jazz-asistant/','X-Title':'Jazz Asistant'},body:JSON.stringify({model,messages,max_tokens:maxTokens,temperature:.55})}),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(provider+'_'+r.status+'_'+String(body?.error?.message||'request_failed').slice(0,180));return{answer:body.choices?.[0]?.message?.content||'',model,usage:body.usage||{}};}
async function gemini(key,messages,maxTokens){const model='gemini-2.5-flash',url='https:'+'//generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent?key='+encodeURIComponent(key),system=messages.filter(x=>x.role==='system').map(x=>x.content).join('\n'),contents=messages.filter(x=>x.role!=='system').map(x=>({role:x.role==='assistant'?'model':'user',parts:[{text:x.content}]})),r=await fetch(url,{method:'POST',signal:AbortSignal.timeout(30000),headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{maxOutputTokens:maxTokens,temperature:.55}})}),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error('gemini_'+r.status+'_'+String(body?.error?.message||'request_failed').slice(0,180));return{answer:body.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'',model,usage:body.usageMetadata||{}};}
async function testModel(provider,key,index){const started=Date.now();try{const messages=[{role:'user',content:'Reply only with OK.'}];provider==='gemini'?await gemini(key,messages,8):await compatible(provider,key,messages,8);return{provider,index,configured:true,ok:true,latencyMs:Date.now()-started};}catch(e){return{provider,index,configured:true,ok:false,error:String(e).replace('Error: ','').slice(0,220),latencyMs:Date.now()-started};}}
async function testNotion(key,index){const started=Date.now();try{const r=await fetch('https:'+'//api.notion.com/v1/users/me',{signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+key,'Notion-Version':'2022-06-28'}});return{provider:'notion',index,configured:true,ok:r.ok,status:r.status,latencyMs:Date.now()-started};}catch{return{provider:'notion',index,configured:true,ok:false,status:0,latencyMs:Date.now()-started};}}
async function diagnostics(){const jobs=[];for(const provider of ['groq','openrouter','openai','gemini'])pools[provider].forEach((key,i)=>jobs.push(testModel(provider,key,i+1)));pools.notion.forEach((key,i)=>jobs.push(testNotion(key,i+1)));return{configured:{groq:pools.groq.length,openrouter:pools.openrouter.length,openai:pools.openai.length,gemini:pools.gemini.length,notion:pools.notion.length},results:await Promise.all(jobs)};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);if(!takeQuota(req))return json({error:'public_test_rate_limit'},429);try{const body=await req.json();if(body.action==='diagnostics')return json(await diagnostics());const input=Array.isArray(body.messages)?body.messages:[],maxTokens=Math.max(64,Math.min(Number(body.maxTokens)||4096,8192)),messages=[{role:'system',content:'Sen Jazz Asistant adlı kişisel çalışma asistanısın. Gizli bilgileri açıklama. Notion içeriğini bu genel test modunda okuma veya değiştirme.'},...input.slice(-40).map(x=>({role:['system','user','assistant'].includes(x.role)?x.role:'user',content:String(x.content||'').slice(0,30000)}))],order=(Array.isArray(body.providers)?body.providers:['groq','openrouter','openai','gemini']).filter(x=>pools[x]?.length);let last='no_provider_keys';for(const provider of order)for(let i=0;i<pools[provider].length;i++)try{const started=Date.now(),out=provider==='gemini'?await gemini(pools[provider][i],messages,maxTokens):await compatible(provider,pools[provider][i],messages,maxTokens);return json({...out,provider,keyIndex:i+1,latencyMs:Date.now()-started,mode:'public-test'});}catch(e){last=String(e).replace('Error: ','');}return json({error:last.slice(0,300)},502);}catch(e){return json({error:String(e).replace('Error: ','').slice(0,300)},400);}});
